blog/urls.py
from django.urls import path #url 불러오기
from . import views

urlpatterns = [#서버 IP/blog/

    path('search/<str:q>/', views.PostSearch.as_view()),
    path('<int:pk>/new_comment/',views.new_comment),
    path('update_post/<int:pk>/',views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>',views.tag_page),
    path('category/<str:slug>',views.category_page),
    path('<int:pk>', views.PostDetail.as_view()),
    path('',views.PostList.as_view())
]

hwInternetPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('shopping/', include('shopping.urls')),
    path('admin/', admin.site.urls),
    path('', include('single_pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myInternetPrj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('blog/', include('blog.urls')),#서버 IP/blog, 블로그에 있는 url 인클로드. 블로그에 urls파일 추가
    path('admin/', admin.site.urls), #서버IP/admin
    path('', include('single_pages.urls')), #서버IP/로 사바ip만 들어오고 아무것도 없으면 include()안 링크로 연결
    path('accounts/',include('allauth.urls')),
    path('markdownx/',include('markdownx.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #서버 fhIP/media/

shopping/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/',views.new_comment),
    path('', views.PostList.as_view()),
]

shopping/models.py
from django.db import models
from django.contrib.auth.models import User
import os
# Create your models here.
from markdown import markdown
from markdownx.models import MarkdownxField
from datetime import timedelta

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shopping/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = MarkdownxField()
    price_text = models.CharField(max_length=50)
    capacity_text = models.CharField(max_length=50, blank=True)
    kcal_text = models.CharField(max_length=100, blank=True)
    produce_text =models.CharField(max_length=100, blank=True)
    head_image = models.ImageField(upload_to='shopping/images/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/shopping/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://doitdjango.com/avatar/id/425/9afec6c6a50ba0ce/svg/{self.author.email}/'

    def is_updated(self):
        return self.updated_at - self.created_at > timedelta(seconds=1)

shopping/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model =Comment
        fields = ('content',)

shopping/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import ListView,DetailView,CreateView, UpdateView
from .models import Post,Category,Comment
from .forms import CommentForm
# Create your views here.

class PostCreate(LoginRequiredMixin,UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'price_text', 'content', 'head_image', 'capacity_text', 'produce_text','kcal_text','category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/shopping/')

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post,pk=pk)

        if request.method =='POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
                return redirect(post.get_absolute_url())
    else :
        raise PermissionDenied

class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = '5'

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context



class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)
            #| Q(tags__name__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context



class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'price_text', 'content', 'head_image', 'capacity_text','category']
    template_name = 'shopping/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        current_user = self.request.user
        if request.user.is_authenticated == current_user.is_staff or current_user.is_superuser:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'shopping/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category
        }
    )
class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post

    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

shopping/templates/shopping/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block head_title %}쇼핑몰 | 음료수,차,커피 다양하게 즐기세요{% endblock %}</title>
        <link href="{% static 'shopping/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- <link href="./practice.css" rel="stylesheet" type="text/css"> -->
      <script src="https://kit.fontawesome.com/6d1439ca4d.js" crossorigin="anonymous"></script>

    </head>
     <body>
        {% include 'shopping/navbar.html' %}

        <div class="container">
    <div class="row my-3">
        <div class="col-md-8 col-lg-9" id="main-area">
            {% block main_area %}
            {% endblock %}
        </div>
        <div class="col-md-4 col-lg-3">
            <!-- Search Widget -->
            <div class="card my-4">
                <div class="card-header">
                    <i class="fas fa-search"></i>&nbsp;&nbsp;Search</div>
                <div class="card-body">

                        <div class="input-group-btn">
                            <input class="form-control" type="text" id="search-input" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-secondary" type="button" onclick="searchPost();">Go!</button>

                        </div>

                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4" id="categories-card">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">

                        <ul>
                            {% for category in categories %}
                            <li>
                                <a href="{{ category.get_absolute_url }}">{{ category.name }} ({{ category.post_set.count }})</a>
                            </li>
                            {% endfor %}
                            <li>
                                <a href="/shopping/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                            </li>
                        </ul>


                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
<script>
    function searchPost(){
        let searchValue = document.getElementById('search-input').value.trim();
        if (searchValue.length > 0){
            location.href="/shopping/search/" + searchValue + "/";
        }
        else{
            alert('검색어('+ searchValue +')가 너무 짧습니다.');
        }
    };

    document.getElementById('search-input').addEventListener('keyup', function(event){
        if(event.key === 'Enter'){
            searchPost();
        }
    });
</script>

{% include 'shopping/footer.html' %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

shopping/templates/shopping/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <title>{% block head_title %}쇼핑몰 | 음료수,차,커피 다양하게 즐기세요{% endblock %}</title>
        <link href="{% static 'shopping/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <!-- <link href="./practice.css" rel="stylesheet" type="text/css"> -->
      <script src="https://kit.fontawesome.com/6d1439ca4d.js" crossorigin="anonymous"></script>
    </head>

     <body>

        {% include 'shopping/navbar.html' %}
        <div class="container mt-3">
        <div class="row">
            <div class="col-12" id="main-area">
                {% block main_area %}
                {% endblock %}
            </div>
        </div>
        </div>



{% include 'shopping/footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
</body>
</html>

shopping/templates/shopping/comment_form.html
{% extends 'shopping/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Comment {% endblock %}

{% block main_area %}
<h1>Edit Comment</h1>
<hr/>
<form method="post" id="comment-form">{% csrf_token %}
    {{ form | crispy }}
    <br/>
    <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>
{% endblock %}

shopping/templates/shopping/footer.html
<!-- Footer -->
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">나만의 음료 &copy;
        <span>대표이사 : 김oo</span>	<span>주소 : 김포시 풍무로 69 000번지 (skywater건물)</span><br>
				<span>사업자등록번호 : 102-81-11112</span>
            <span>음료 고객상담실 : 080-123-9999 , 전화주문 / 세금계산서 / 신규거래 : 1588-0000"</span>
        </p>
    </div>
    <!-- /.container -->
</footer>

shopping/templates/shopping/navbar.html
{% load socialaccount %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">음료모아 </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ">
        <li class="nav-item active">
          <a class="nav-link" href="/shopping/"> mall </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about_me/">Company</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/">홈</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/my_information/">MY 페이지 </a>
          </li>

      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             {% if user.socialaccount_set.all.0.get_avatar_url %}
             <img class="rounded-circle" width="25px"
             src="{{user.socialaccount_set.all.0.get_avatar_url}}">
             {% else %}
             <img class="rounded-circle" width="25px"
             src="https://doitdjango.com/avatar/id/425/9afec6c6a50ba0ce/svg/{user.email}/">
             {% endif %}
             {{user.username}}
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="dropdown-item" href="/accounts/logout/">
               Log Out
             </a>
           </div>
         </li>
        {% else %}
        <li class="nav-item">

          <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">
            Log In</a>
        </li>
        {% endif %}
    </ul>
    </div>
  </nav>

  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel"><i class="fas fa-sign-in-alt"></i> &nbsp;&nbsp;Log In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6">
            <a role="button" class="btn btn-outline-dark btn-block btn-sm"
            href="{% provider_login_url 'google' %}">
              <i class="fab fa-google"></i>&nbsp;&nbsp;Log in with Google
            </a>
            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/"><i class="fas fa-envelope"></i>&nbsp;&nbsp;Log in with Email</a>
          </div>
          <div class="col-md-6">
            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup/"><i class="fas fa-envelope"></i>&nbsp;&nbsp;Sing Up with Email </a>
             <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/naver"><i class="fas fa-envelope"></i>&nbsp;&nbsp;Log in with Naver</a>
          </div>
        </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
  </div>

shopping/templates/shopping/post_detail.html
{% extends 'shopping/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ post.title }} | Blog
{% endblock %}

{% block main_area %}
<div id="post-area">
    {% if post.category %}
    <span class="badge badge-secondary float-right">{{ post.category }}</span>
    {% else %}
    <span class="badge badge-secondary float-right">미분류</span>
    {% endif %}

    <!-- Title -->
    <h1 class="mt-4">{{ post.title }}</h1>
    {% if post.price_text %}
    <h5 class="text-muted">{{ post.price_text }}</h5>
    {% endif %}

    {% if post.capacity_text %}
    <h5 class="text-muted">{{ post.capacity_text }}</h5>
    {% endif %}

    {% if post.kcal_text %}
    <h5 class="text-muted">{{ post.kcal_text }}</h5>
    {% endif %}

    <!-- Author -->
    <p class="lead">
        by
       <a href="#">{{ post.author | upper }}</a>
    </p>

    {% if post.produce_text %}
    <h5 class="text-muted">{{ post.produce_text }}</h5>
    {% endif %}

    <hr>
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
            <a type="button" href="/shopping/update_post/{{ post.pk }}/" class="btn btn-info btn-sm float-right"><i class="fas fa-pen"></i>&nbsp;&nbsp; Edit Post</a>
        {% endif %}
    {% endif %}



    <!-- Preview Image -->
    {% if post.head_image %}
    <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }}">
    {% else %}
    <img class="card-img-top" src="https://picsum.photos/seed/{{ post.id }}/600/200" alt="{{ p.title }}">
    {% endif %}

    <hr>

        <!-- Post Content -->
    <p>{{ post.get_content_markdown | safe }}</p>
<!-- Date/Time -->
    <hr>
    <p>Posted on {{ post.created_at }}</p>

    <hr>
</div>


<!-- Comments section-->
    <div class="mb-5" id="comment-area">
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
                    {% if user.is_authenticated %}
                    <form class="mb-4" id="comment-form" method="POST" action="{{ post.get_absolute_url}}new_comment/">
                         {% csrf_token %}
                         <div class="form-group">
                            {{ comment_form | crispy }}
                        </div>
                         <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    {% else %}
                        <a role="button" type="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">Log in and leave a comment</a>
                    {% endif %}



            {% if post.comment_set.exists %}
            {% for comment in post.comment_set.iterator %}
                <!-- Single Comment -->
                <div class="media mb-4" id="comment-{{ comment.pk }}">
                    <img class="d-flex mr-3 rounded-circle" src="{{ comment.get_avatar_url }}" alt="{{ comment.author }}" width="60px">
                    <div class="media-body">
                        {% if user.is_authenticated and comment.author == user %}
                        <div class="float-right">
                <a class="btn btn-sm btn-info"
                   role="button"
                   id="comment-{{ comment.pk }}-update-btn"
                   href="/shopping/update_comment/{{ comment.pk }}/">edit</a>
                <a class="btn btn-sm btn-danger"
                   role="button"
                   id="comment-{{ comment.pk }}-delete-btn"
                   data-toggle="modal"
                   data-target="#deleteCommentModal-{{ comment.pk }}"
                   href="/">delete</a>
            </div>

            <!-- Modal {{ comment.pk }} -->
            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" aria-labelledby="delteCommentModal-{{ comment.pk }}-ModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteCommentModalLabel-{{ comment.pk }}">Are You Sure?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <del>{{ comment | linebreaks }}</del>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <a role="button"
                               type="button"
                               class="btn btn-danger"
                               href="/shopping/delete_comment/{{ comment.pk }}/">
                                Delete
                            </a>
                        </div>
                    </div>
                </div>
            </div>
                        {% endif %}
                        <h5 class="mt-0">{{ comment.author.username }} &nbsp;&nbsp; <small class="text-muted">{{ comment.created_at }}</small></h5>
                        {{ comment.content | linebreaks }}
                        {% if comment.is_updated %}
                            <p class="text-muted float-right">Updated: {{ comment.updated_at }}</p>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    </div>
{% endblock %}

shopping/templates/shopping/post_form.html
{% extends 'shopping/base_full_width.html' %}

{% load crispy_forms_tags %}
{% block head_title%}
Create Post
{% endblock %}

{% block main_area %}
<h1>Create a New Post</h1>
<hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
             {{ form | crispy }}
        </table>

        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{form.media}}
{% endblock %}

shopping/templates/shopping/post_list.html
{% extends 'shopping/base.html' %}

{% block main_area %}
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
            <a type="button" href="/shopping/create_post/" class="btn btn-info btn-sm float-right"><i class="fas fa-pen"></i>&nbsp;&nbsp;NEW PRODUCT</a>
        {% endif %}
    {% endif %}
    <h1>
        {% if search_info %}<span class="badge badge-secondary">{{ search_info }}</span>{% endif %}
        {% if category %}
            <span class="badge badge-secondary">{{ category }}</span>
        {% endif %}
    </h1>
<br>
    {% if post_list.exists %}
        {% for p in post_list %}
        <!-- Blog Post -->
        <div class="card mb-4" id="post-{{ p.id }}">
            {% if p.head_image %}
            <img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p.title }}">
            {% else %}
            <img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/600/200" alt="{{ p.title }}">
            {% endif %}
            <div class="card-body">
                {% if p.category %}
                <span class="badge badge-secondary float-right">{{ p.category }}</span>
                {% else %}
                <span class="badge badge-secondary float-right">미분류</span>
                {% endif %}

                <h2 class="card-title">{{ p.title }}</h2>
                {% if p.price_text %}
                <h5 class="text-muted">{{ p.price_text }}</h5>
                {% endif %}
                  <p class="card-text">{{ p.get_content_markdown | truncatewords_html:30 | safe }}</p>
                 <a href="{{ p.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>

            <div class="card-footer text-muted">
                Posted on {{ p.created_at }} by
                 <a href="#">{{ p.author | upper }}</a>
            </div>

        </div>
        {% endfor %}

    {% else %}
         <h1>아직 게시물이 없습니다</h1>
    {% endif %}


    <!-- Pagination -->
   {% if is_paginated %}
        <ul class="pagination justify-content-center mb-4">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><-Newer </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#"><-Newer </a>
                </li>
            {% endif %}
             {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Older-></a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Older-></a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

shopping/templates/shopping/post_update_form.html
{% extends 'shopping/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title%}Edit Post - Blog{% endblock %}

{% block main_area %}


<h1>Edit Post</h1>
<hr/>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{ form | crispy }}
    </table>
    <br>
    <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>



{{ form.media }}
{% endblock %}